#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Ottenheimer GmbH
"""Generate a per-asset miss report for one tool, for sending to its vendor.

    tools/miss-report.py --results runs/<run>/results/results.json --tool <name>

A vendor needs the *shape* of each miss to fix it. It does not need the corpus.
This report is therefore built from ground-truth metadata only and deliberately
omits three things:

* **file paths** -- the directory layout is part of what the corpus withholds;
* **line numbers** -- likewise, and a vendor tuning to line numbers would be
  tuning to this corpus rather than to finding cryptography;
* **corpus file contents** -- never read by this tool at all.

What it does carry is the layer, the language, the file *format*, the asset's
category identifier, the expected algorithm and asset type, and three
diagnostics saying how close the attempt came. That is enough to reproduce and
fix a miss without being enough to reconstruct the corpus.

The earlier edition of this report was produced by hand. This exists so the
numbers a vendor receives are regenerable from a results file rather than
retyped.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

LAYER_TITLES = {
    1: "call-site algorithm use",
    2: "aliased import",
    3: "wrapper indirection",
    4: "configuration-declared algorithm",
    5: "dependency manifest",
    6: "key material and keystores",
}


def file_format(path: str) -> str:
    """Return only the extension of a path, never the path itself."""
    suffix = Path(path).suffix
    return f"`{suffix}`" if suffix else "`(no extension)`"


def flag(value: bool) -> str:
    return "yes" if value else "no"


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--results", type=Path, required=True, help="results.json from score.py")
    parser.add_argument("--tool", required=True, help="tool name to report on")
    parser.add_argument("--out", type=Path, help="output file (default: stdout)")
    args = parser.parse_args()

    document = json.loads(args.results.read_text(encoding="utf-8"))
    meta = document.get("meta", {})
    results = [r for r in document["results"] if r["tool"] == args.tool]
    if not results:
        print(f"no results for tool {args.tool!r} in {args.results}", file=sys.stderr)
        return 1

    misses: list[dict] = []
    detected = total = 0
    for result in results:
        for asset in result["assets"]:
            total += 1
            if asset["detected"]:
                detected += 1
                continue
            misses.append({**asset, "project": result["project"], "language": result["language"]})

    by_layer: dict[int, list[dict]] = {}
    for miss in misses:
        by_layer.setdefault(miss["layer"], []).append(miss)

    out: list[str] = []
    out.append(f"# {args.tool}: per-asset miss report\n\n")
    corpus = meta.get("corpus", "public")
    out.append(
        f"{corpus.capitalize()} corpus at `{meta.get('corpus_version', 'unknown')}`, "
        f"line tolerance {meta.get('line_tolerance')}.\n"
        "Generated by `tools/miss-report.py` from ground-truth metadata only. It contains no\n"
        "corpus file contents, and deliberately no file paths or line numbers: the shape of\n"
        "each miss is what a vendor needs to fix it, and the locations are the corpus's to keep.\n\n"
    )
    out.append(f"**{len(misses)} missed assets of {total}.**\n\n")

    out.append("## Summary\n\n")
    rows = [
        [str(layer), LAYER_TITLES.get(layer, "?"), str(len(by_layer.get(layer, [])))]
        for layer in sorted(LAYER_TITLES)
    ]
    out.append("| layer | what it tests | missed |\n| --- | --- | --- |\n")
    for row in rows:
        out.append(f"| {row[0]} | {row[1]} | {row[2]} |\n")
    out.append("\n")

    out.append("## How to read a row\n\n")
    out.append(
        "`shape` is the ground-truth asset identifier. It names the construct category,\n"
        "not its location. `expected algorithm` is what a correct detection must name,\n"
        "subject to the matcher's family and alias rules, so `SHA-2` for `SHA-256` is\n"
        "accepted. `asset type` is the CycloneDX `cryptoProperties.assetType` the asset\n"
        "should carry. The three diagnostic columns say how close the attempt came:\n\n"
        "- **located**: a claim landed on the right file and line but named an\n"
        "  incompatible algorithm. A naming problem, not a detection problem.\n"
        "- **file only**: a claim landed in the right file, wrong line.\n"
        "- **name only**: the algorithm name appears somewhere in the document with no\n"
        "  evidence tying it to the site. Not a detection.\n\n"
        "All three false across a row means nothing was reported for that asset.\n\n"
    )

    header = (
        "| project | language | format | shape | expected algorithm | asset type "
        "| located | file only | name only |\n"
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n"
    )
    for layer in sorted(LAYER_TITLES):
        entries = by_layer.get(layer, [])
        out.append(f"## Layer {layer}: {LAYER_TITLES[layer]} ({len(entries)} missed)\n\n")
        if not entries:
            out.append("None. Every planted asset in this layer was detected.\n\n")
            continue
        out.append(header)
        for miss in sorted(entries, key=lambda m: (m["project"], m["id"])):
            out.append(
                f"| {miss['project']} | {miss['language']} | {file_format(miss['file'])} "
                f"| `{miss['id']}` | {miss['algorithm']} | {miss['cyclonedx_asset_type']} "
                f"| {flag(miss['located'])} | {flag(miss['file_only'])} "
                f"| {flag(miss['name_only'])} |\n"
            )
        out.append("\n")

    rendered = "".join(out)
    if args.out:
        args.out.write_text(rendered, encoding="utf-8")
        print(f"wrote {args.out} ({len(misses)} misses of {total})")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
