# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Ottenheimer GmbH
"""Rendering results as Markdown matrices and JSON."""

from __future__ import annotations

from collections import defaultdict

from .scoring import ScoreResult

LAYER_TITLES = {
    1: "L1 direct call",
    2: "L2 aliased import",
    3: "L3 wrapper",
    4: "L4 config",
    5: "L5 declared dep",
    6: "L6 key/cert file",
}


def _table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "_No data._\n"
    widths = [len(h) for h in headers]
    for row in rows:
        for index, cell in enumerate(row):
            widths[index] = max(widths[index], len(cell))

    def render(cells: list[str]) -> str:
        return "| " + " | ".join(cell.ljust(widths[i]) for i, cell in enumerate(cells)) + " |"

    lines = [render(headers), "|" + "|".join("-" * (w + 2) for w in widths) + "|"]
    lines.extend(render(row) for row in rows)
    return "\n".join(lines) + "\n"


def _pct(hit: int, total: int) -> str:
    if not total:
        return "--"
    return f"{100 * hit / total:.0f}% ({hit}/{total})"


def _render_provenance(meta: dict) -> str:
    """State what produced these numbers.

    A matrix that cannot be traced to the run that produced it is a claim rather
    than a measurement, so the manifest's contents are reproduced here instead of
    being left in a file nobody opens.
    """
    run = meta.get("run")
    if not run:
        return (
            "\n> No run manifest was supplied, so these results record no tool versions.\n"
            "> Pass `--manifest` for a publishable run; see METHODOLOGY.md §8.\n"
        )

    out = ["\n## Provenance\n\n"]
    rows = [
        ["run started", run.get("started_utc") or "--"],
        ["corpus commit", run.get("corpus_commit") or "--"],
        ["corpus tree dirty", "yes -- NOT PUBLISHABLE" if run.get("corpus_tree_dirty") else "no"],
        ["manifest", run.get("manifest") or "--"],
        ["line tolerance", str(meta.get("line_tolerance"))],
        [
            "invocations",
            f"{run.get('succeeded', '?')} of {run.get('attempted', '?')} produced a document",
        ],
    ]
    out.append(_table(["", ""], rows))

    versions = run.get("tool_versions") or {}
    if versions:
        out.append("\n### Tool versions\n\n")
        out.append(_table(["tool", "self-reported version"], [[k, v or "--"] for k, v in sorted(versions.items())]))

    tables = run.get("judgement_tables") or {}
    if tables:
        out.append("\n### Judgement tables\n\n")
        out.append(
            "Digests of the tables that encode judgement rather than fact "
            "(METHODOLOGY.md §9.1). A score that moves because one of these moved is "
            "attributable rather than invisible.\n\n"
        )
        out.append(
            _table(
                ["table", "entries", "sha256/16"],
                [
                    [name, str(spec.get("entries", "?")), spec.get("sha256_16", "?")]
                    for name, spec in sorted(tables.items())
                ],
            )
        )

    failures = run.get("failed_invocations") or []
    if failures:
        out.append("\n### Invocations that produced no document\n\n")
        out.append(
            "These are why a (project, tool) pair is absent from the tables below. They are "
            "**not** scored as zero: a generator that did not run has not missed anything.\n\n"
        )
        out.append(
            _table(
                ["tool", "project", "status", "detail"],
                [
                    [
                        f["tool"],
                        f["project"],
                        f["status"],
                        (f.get("error") or f.get("stderr_tail") or "")[:80],
                    ]
                    for f in failures
                ],
            )
        )

    return "".join(out)


def render_markdown(results: list[ScoreResult], meta: dict) -> str:
    tools = sorted({r.tool for r in results})
    languages = sorted({r.language for r in results})

    out: list[str] = []
    out.append("# Proofstein results\n")
    corpus = meta.get("corpus", "public")
    out.append(
        f"Generated by `score.py` against the **{corpus} corpus** at "
        f"`{meta.get('corpus_version', 'unknown')}`, line tolerance "
        f"{meta['line_tolerance']}.\n"
    )
    if corpus == "holdout":
        out.append(
            "\n> **Holdout results.** These are reported separately from public-corpus "
            "scores and are never averaged with them. A large gap between a tool's public "
            "and holdout scores is the finding the holdout exists to produce.\n"
        )
    out.append(
        "**A detection requires agreement on file and line.** An algorithm name on its own is "
        "never counted as a detection; the name-only column exists to show what such a metric "
        "would have claimed. See METHODOLOGY.md for the matching rules.\n"
    )

    if meta.get("unscored_pairs"):
        out.append(
            f"\n> {meta['unscored_pairs']} (project, tool) pair(s) present in the corpus were not "
            "found in the input and are excluded from every table below, rather than "
            "counted as zero.\n"
        )

    out.append(_render_provenance(meta))

    # ---- headline: detection rate by tool and language -------------------
    out.append("\n## Detection rate by language\n")
    out.append("File-and-line agreement plus a credible algorithm name.\n\n")
    rows = []
    for tool in tools:
        row = [tool]
        for language in languages:
            subset = [r for r in results if r.tool == tool and r.language == language]
            hit = sum(r.detected for r in subset)
            total = sum(r.total for r in subset)
            row.append(_pct(hit, total))
        subset = [r for r in results if r.tool == tool]
        row.append(_pct(sum(r.detected for r in subset), sum(r.total for r in subset)))
        rows.append(row)
    out.append(_table(["tool", *languages, "all"], rows))

    # ---- detection rate by layer ----------------------------------------
    out.append("\n## Detection rate by layer\n")
    out.append("The layers are what the corpus is for: they separate a generator that\n")
    out.append("pattern-matches call sites from one that follows indirection.\n\n")
    layers = sorted(LAYER_TITLES)
    rows = []
    for tool in tools:
        row = [tool]
        for layer in layers:
            hit = total = 0
            for result in (r for r in results if r.tool == tool):
                got, count = result.by_layer().get(layer, (0, 0))
                hit += got
                total += count
            row.append(_pct(hit, total))
        rows.append(row)
    out.append(_table(["tool", *[LAYER_TITLES[layer] for layer in layers]], rows))

    # ---- per language per layer -----------------------------------------
    out.append("\n## Detection rate by language and layer\n")
    for language in languages:
        out.append(f"\n### {language}\n\n")
        rows = []
        for tool in tools:
            subset = [r for r in results if r.tool == tool and r.language == language]
            if not subset:
                continue
            row = [tool]
            for layer in layers:
                hit = total = 0
                for result in subset:
                    got, count = result.by_layer().get(layer, (0, 0))
                    hit += got
                    total += count
                row.append(_pct(hit, total))
            rows.append(row)
        out.append(_table(["tool", *[LAYER_TITLES[layer] for layer in layers]], rows))

    # ---- evidence quality ------------------------------------------------
    out.append("\n## Evidence quality\n")
    out.append(
        "A generator cannot be credited with a detection it provides no way to check.\n"
        "`with line` is the ceiling on any tool's detection rate here.\n\n"
    )
    rows = []
    for tool in tools:
        subset = [r for r in results if r.tool == tool]
        components = sum(r.evidence.crypto_components for r in subset)
        with_location = sum(r.evidence.with_location for r in subset)
        with_line = sum(r.evidence.with_line for r in subset)
        spec = sum(r.evidence.using_spec_evidence for r in subset)
        props = sum(r.evidence.using_properties_only for r in subset)
        occurrences = sum(r.evidence.total_occurrences for r in subset)
        unresolvable = sum(r.evidence.unresolvable_locations for r in subset)
        rows.append(
            [
                tool,
                str(components),
                _pct(with_location, components),
                _pct(with_line, components),
                _pct(spec, components),
                str(props),
                f"{occurrences / components:.2f}" if components else "--",
                str(unresolvable),
            ]
        )
    out.append(
        _table(
            [
                "tool",
                "crypto components",
                "with file",
                "with line",
                "via evidence.occurrences",
                "properties only",
                "occurrences/component",
                "unresolvable paths",
            ],
            rows,
        )
    )

    # ---- what a weaker metric would have claimed -------------------------
    out.append("\n## What weaker matching rules would have claimed\n")
    out.append(
        "Same inputs, progressively weaker rules. The gap between the first and last\n"
        "column is the amount of credit an algorithm-name-only benchmark hands out for free.\n\n"
    )
    rows = []
    for tool in tools:
        subset = [r for r in results if r.tool == tool]
        total = sum(r.total for r in subset)
        detected = sum(r.detected for r in subset)
        located = sum(sum(1 for v in r.verdicts if v.located) for r in subset)
        file_only = sum(sum(1 for v in r.verdicts if v.file_only) for r in subset)
        name_only = sum(sum(1 for v in r.verdicts if v.name_only) for r in subset)
        rows.append(
            [
                tool,
                _pct(detected, total),
                _pct(located, total),
                _pct(file_only, total),
                _pct(name_only, total),
            ]
        )
    out.append(
        _table(
            [
                "tool",
                "file+line+algorithm (reported)",
                "file+line, any name",
                "file only",
                "name only (NOT a detection)",
            ],
            rows,
        )
    )

    # ---- precision -------------------------------------------------------
    out.append("\n## Precision\n")
    out.append(
        "Detection rate on its own is gameable: a generator that claimed every algorithm at\n"
        "every line of every file would be credited with finding everything.\n\n"
        "**Claim precision is the check on that**, not component precision. Component\n"
        "precision can be defeated by packing the guesses into a few components -- ten\n"
        "components each carrying an occurrence for every line reach full recall at 80%\n"
        "component precision. Counting individual evidence claims prices every guess: the\n"
        "same document credits 19 claims out of 7670.\n\n"
        "An honest generator makes about one claim per site it found, so its two figures sit\n"
        "close together. A wide gap between them is the signature of guessing.\n\n"
    )
    rows = []
    for tool in tools:
        subset = [r for r in results if r.tool == tool]
        matched = sum(r.matched_components for r in subset)
        reported = sum(r.evidence.crypto_components for r in subset)
        credited = sum(r.credited_claims for r in subset)
        claims = sum(r.evidence.distinct_claims for r in subset)
        detected = sum(r.detected for r in subset)
        total = sum(r.total for r in subset)
        rows.append(
            [
                tool,
                _pct(credited, claims),
                _pct(matched, reported),
                str(claims),
                str(reported),
                _pct(detected, total),
            ]
        )
    out.append(
        _table(
            [
                "tool",
                "claim precision",
                "component precision",
                "claims made",
                "components reported",
                "recall (detection rate)",
            ],
            rows,
        )
    )

    # ---- schema validity and false positives -----------------------------
    out.append("\n## Schema validity and false positives\n")
    out.append(
        "`phantom file` means evidence pointed at a path that is not in the project.\n"
        "`phantom algorithm` means a family that appears nowhere in it.\n"
        "`unmatched` reports sit at a real location with no planted asset: the corpus\n"
        "ground truth is complete for planted assets, not exhaustive of every construct,\n"
        "so these are shown but never charged against a tool.\n\n"
    )
    rows = []
    for tool in tools:
        subset = [r for r in results if r.tool == tool]
        validated = [r for r in subset if r.schema_valid is not None]
        valid = sum(1 for r in validated if r.schema_valid)
        rows.append(
            [
                tool,
                _pct(valid, len(validated)) if validated else "not run",
                str(sum(r.phantom_location for r in subset)),
                str(sum(r.phantom_algorithm for r in subset)),
                str(sum(r.false_positives for r in subset)),
                str(sum(r.unmatched_reports for r in subset)),
                str(sum(1 for r in subset if r.parse_error)),
            ]
        )
    out.append(
        _table(
            [
                "tool",
                "schema valid",
                "phantom file",
                "phantom algorithm",
                "false positives",
                "unmatched (uncharged)",
                "unparseable",
            ],
            rows,
        )
    )

    # ---- per project detail ---------------------------------------------
    out.append("\n## Per project\n\n")
    rows = []
    for result in sorted(results, key=lambda r: (r.language, r.project, r.tool)):
        spread = " ".join(
            f"{layer}:{hit}/{total}" for layer, (hit, total) in sorted(result.by_layer().items())
        )
        rows.append(
            [
                result.project,
                result.language,
                result.tool,
                _pct(result.detected, result.total),
                spread,
                str(result.false_positives),
                {True: "yes", False: "no", None: "--"}[result.schema_valid],
            ]
        )
    out.append(
        _table(["project", "language", "tool", "detected", "by layer", "FP", "schema"], rows)
    )

    if meta.get("problems"):
        out.append("\n## Input problems\n\n")
        for problem in meta["problems"]:
            out.append(f"- {problem}\n")

    return "".join(out)


def render_json(results: list[ScoreResult], meta: dict) -> dict:
    per_tool: dict[str, dict] = defaultdict(
        lambda: {
            "detected": 0,
            "total": 0,
            "false_positives": 0,
            "matched_components": 0,
            "reported_components": 0,
            "credited_claims": 0,
            "total_claims": 0,
            "by_layer": defaultdict(lambda: [0, 0]),
        }
    )

    documents = []
    for result in results:
        summary = per_tool[result.tool]
        summary["detected"] += result.detected
        summary["total"] += result.total
        summary["false_positives"] += result.false_positives
        summary["matched_components"] += result.matched_components
        summary["reported_components"] += result.evidence.crypto_components
        summary["credited_claims"] += result.credited_claims
        summary["total_claims"] += result.evidence.distinct_claims
        for layer, (hit, total) in result.by_layer().items():
            summary["by_layer"][str(layer)][0] += hit
            summary["by_layer"][str(layer)][1] += total

        documents.append(
            {
                "project": result.project,
                "language": result.language,
                "tool": result.tool,
                "source": result.source,
                "schema_valid": result.schema_valid,
                "schema_errors": result.schema_errors,
                "parse_error": result.parse_error,
                "detected": result.detected,
                "total": result.total,
                "detection_rate": result.detection_rate,
                "precision": result.precision,
                "claim_precision": result.claim_precision,
                "matched_components": result.matched_components,
                "credited_claims": result.credited_claims,
                "by_layer": {str(k): {"detected": v[0], "total": v[1]} for k, v in result.by_layer().items()},
                "false_positives": result.false_positives,
                "phantom_location": result.phantom_location,
                "phantom_algorithm": result.phantom_algorithm,
                "unmatched_reports": result.unmatched_reports,
                "evidence": result.evidence.as_dict(),
                "assets": [
                    {
                        "id": v.id,
                        "file": v.file,
                        "line": v.line,
                        "algorithm": v.algorithm,
                        "layer": v.layer,
                        "cyclonedx_asset_type": v.asset_type,
                        "detected": v.detected,
                        "located": v.located,
                        "file_only": v.file_only,
                        "name_only": v.name_only,
                    }
                    for v in result.verdicts
                ],
            }
        )

    tools_summary = {}
    for tool, summary in sorted(per_tool.items()):
        tools_summary[tool] = {
            "detected": summary["detected"],
            "total": summary["total"],
            "detection_rate": round(summary["detected"] / summary["total"], 4)
            if summary["total"]
            else 0.0,
            "precision": round(summary["matched_components"] / summary["reported_components"], 4)
            if summary["reported_components"]
            else 0.0,
            "claim_precision": round(summary["credited_claims"] / summary["total_claims"], 4)
            if summary["total_claims"]
            else 0.0,
            "matched_components": summary["matched_components"],
            "reported_components": summary["reported_components"],
            "credited_claims": summary["credited_claims"],
            "total_claims": summary["total_claims"],
            "false_positives": summary["false_positives"],
            "by_layer": {
                layer: {
                    "detected": counts[0],
                    "total": counts[1],
                    "rate": round(counts[0] / counts[1], 4) if counts[1] else 0.0,
                }
                for layer, counts in sorted(summary["by_layer"].items())
            },
        }

    return {"meta": meta, "tools": tools_summary, "results": documents}
